import Head from "next/head";
import { Inter } from "next/font/google";
import { useQuery } from "urql";
import { PRODUCT_QUERY } from "@/lib/query";
import { Gallery } from "@/styles/Gallery";
import Product from "@/components/product";
import { useStateContext } from "@/lib/context";
import { useEffect } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // GET STATE
  const { resetQty } = useStateContext();

  // RESET QTY
  useEffect(() => resetQty);

  // Fecth products from strapi

  const [results] = useQuery({ query: PRODUCT_QUERY });

  const { data, fetching, error } = results;

  if (fetching) return <p>Loading...</p>;

  if (error) return <p>Error encountered... {error.message}</p>;

  const products = data.products.data;

  return (
    <>
      <Head>
        <title>Verisence</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <main className={inter.className}>
        <Gallery>
          {products.map((product) => (
            <Product
              key={product.attributes.slug}
              product={product}
            />
          ))}
        </Gallery>
      </main>
    </>
  );
}
